version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
        - npm install
  pre_build:
    commands:
        - npm run lint
        - npm run test-post
        - npm run test-user
  build:
    commands:
        - npm run tsc
     
artifacts:
  files:
    - appspec.yml
    - node_modules/**/*
    - build/**/*
    - scripts/*
